server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.222:3306/db2020?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Admin@123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #  所有实体类（Entity）别名类所在包
  type-aliases-package: cn.fanchencloud.springcloud.entity